### ISSUE TITLE
When using com.webos.service.db/putKind, {"errorCode":-3963, "errorText":"db": permission denied","returnValue":false}

### ISSUE THREAD

**Issue by dudgns128** [webosose/website#17]
- com.webos.service.db/putKind
- the values of 'owner' parameter should include **service name**
- the errorcode should include -3963

There was no description of service's bus address in the webOS OSE, so I referred to the webos TV developer.
"luna://com.palm.wifi/status" and "com.example.helloworld" are two examples of service's bus address.
From this point of view, it is estimated that **the address of the service provided by webOS** or **app ID** means **service's bus addres.**
[https://webostv.developer.lge.com/develop/references/webos-service-reference#servicebusid](url)

There is a description of the service in [Docs] -> [Reference] -> [com.webos.service.db]. Here, a value that can be an owner among Parameters in the putKind method is written as **app ID** or **service's bus address.**

As you know, the service name starts with the app ID. If the **app ID** is 'com.domain.app', the **service name** should be 'com.domain.app.service'. So, not only app ID, but also JS service that I named the service can make API calls.
This is where the problem comes from. The screenshot is an example of an error that the 'ls-monitor' tool has identified.

![scrennshot](https://github.com/webosose/website/assets/62577519/f2c5e315-0391-4410-b672-ca69575d4a36)

As far as I understand, service's bus address does not include service name. Therefore, it is argued that it should be able to be the **service name** among the owner of kind. Since the development is carried out by dividing Application Dir and JS service Dir, I think there will be more cases of calling the API through JS Service than directly calling the API from the APP. In relation to this, quite a few people are not finding the cause of the error even in [Community]. **In conclusion, the service name should also be added to the value that can be the owner of kind.**

**However, if the service name is included in the service's bus address, my opinion does not have to be reflected.**

In addition, {Error Code: -3963, Error Text: db: permission denied, Error Description: } should be added to the Error Codes Reference of the putKind method. As seen in the screenshot, it returns an **error code of -3963 as an error for using putKind.** The corresponding content is also not described, so a correction is required.

[https://www.webosose.org/docs/reference/ls2-api/com-webos-service-db/#putkind](url)

Thanks.

**Comment by Heeam-Shin** [comment]
@dudgns128,

Thanks for your reporting.

I'll review this issue and update the documentation in the next release. I'll share progress through this issue ticket.

**Comment by Heeam-Shin** [comment]
@dudgns128,

webOS OSE 2.27.0 has been release on today. Unfortunately, your report cannot be published on webOS OSE 2.27.0. (due to our company's API policy)

However, the internal documentation has already been updated as belows. (And this will definitely be reflected in a future release. Thank you once again for reporting it.)

---- 

Owner of the kind. Only the owner has permission to modify the created kind.

- Use the ID of the app/service which calls the putKind method.
- App/service can only create kinds that they are the owner of. But it is possible to grant access to the created kind to other apps/services using the putPermission method.

| Error Code | Error Code Text | Description | 
| ------------ | ----------------- | ------------ |
| -3963 | db: permission denied | This message implies that the app does not have permission to delete the specified object. |

**Comment by Heeam-Shin** [comment]
@dudgns128,

It's been a long time since you reported this issue. We're pleased to inform you that the API doc reflecting your issue has been release today ([com.webos.service.db/putKind](https://www.webosose.org/docs/reference/ls2-api/com-webos-service-db/#putkind)).

Again, thanks for your report! Have a nice day.
